### ISSUE TITLE
Feature `declaration expression' cannot be used because it is not part of the C# 6.0 language specification

### ISSUE THREAD

**Issue by Arakis** [xamarin/xamarin-android-tools#12]
when compiling on Debian with Mono (version 4.6.2) i get this error message:

```
AndroidVersions.cs(97,36): error CS1644: Feature `declaration expression' cannot be used because it is not part of the C# 6.0 language specification
``` 

After fixing AndroidVersions.cs, the project can be compiled.

**Comment by jonpryor** [comment]
The `xamarin-android-tools` project might be compilable, but the [Java.Interop](http://github.com/xamarin/Java.Interop) project almost certainly will *not* compile, as it is now using C#7 features.

You're going to need a more recent toolchain. :-(
