### ISSUE TITLE
AndroidToolTask should capture all tool output

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android-tools#208]
Context: https://github.com/xamarin/xamarin-android/commit/b002dc38196a0bedb18c82d228056e1ba108459c
Context: https://github.com/dotnet/maui/issues/14531

Once Upon A Time™ (about a year ago), if we got a `java` failure, the cause of the error could be unscrutable:

    error : java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException:
    Compilation failed to complete, origin: obj/Debug/net7.0-android/lp/59/jl/classes.jar :
    android/support/v4/app/INotificationSideChannel$Stub.class

*Why* did it fail?  To find out we'd invariably have to ask for a diagnostic build log, because only the diagnostic build log contained the full output of `r8.jar`, which would contain the "root" error:

    Type android.support.v4.app.INotificationSideChannel$Stub is defined multiple times:

`java` invocations are not the only place this "inscrutable error messaging" scenario comes up.  Enter XA3006 (via dotnet/maui#14531):

    error XA3006: Could not compile native assembly file: environment.arm64-v8a.ll
    error XA3006: 
    error XA3006: 

How helpful!  How *actionable*!

Yet again, we need to ask for diagnostic build log information (which became a problem on its own right…).

***Enough!***

Update `AndroidToolTask` so that it provides output logging infrastructure, a'la xamarin/xamarin-android@b002dc38, such that *all* tool output is *always* captured (as well as logged via `LogDebugMessage()`), and when an error occurs, *all captured output is part of the error message*.

We can then update `JavaToolTask` and other subclasses to use this common infrastructure.

**Comment by pjcollins** [comment]
I've been looking into this, but haven't found any immediate areas that need improvement. With respect to `AndroidToolTask`:

 * [`AndroidToolTask`](https://github.com/xamarin/xamarin-android-tools/blob/099fd95f5459d9df78af0ad28f46e3016dd7ca1d/src/Microsoft.Android.Build.BaseTasks/AndroidToolTask.cs) extends [`ToolTask`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.build.utilities.tooltask?view=msbuild-17-netcore), which already prints all output as `Normal` importance messages when tool execution does not complete successfully.
 * Our [`AndroidRunToolTask`](https://github.com/xamarin/xamarin-android-tools/blob/8ea78a4fb98cf5b30e87dfb6b9f99f485e297412/src/Microsoft.Android.Build.BaseTasks/AndroidRunToolTask.cs) provides a common regex that can be used to capture and report issues when running an Android SDK tool.
 * As mentioned, the `JavaToolTask` already works in a similar manner to `AndroidRunToolTask`.

With respect to maui#14531, it doesn't appear that any of the provided diagnostic build logs contained additional stdout/stderr from the `llc` tool invocation that failed. The error messaging in the [`CompileNativeAssembly`](https://github.com/xamarin/xamarin-android/blob/main/src/Xamarin.Android.Build.Tasks/Tasks/CompileNativeAssembly.cs) task was already improved in commit 77584e02 to log stdout from the tool was logged when a failure occurred.

We could consider adding a common `System.Diagnostic.Process` wrapper with log on error logic that could be re-used by tasks that inherit from `AndroidAsyncTask` (abstract out [this piece of `CompileNativeAssembly`](https://github.com/xamarin/xamarin-android/blob/77584e02a86fcd01fc85fe6870decf36a4690656/src/Xamarin.Android.Build.Tasks/Tasks/CompileNativeAssembly.cs#L65-L99) for instance), and while that would be useful for the future it wouldn't immediately improve the task.

@dellis1972 do you have any other thoughts here? Maybe I am overlooking something?

**Comment by jonpryor** [comment]
@pjcollins: ran across an instance where I think this applies: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1875239

The scenario: the [`<AndroidAdb/>` task](https://github.com/xamarin/xamarin-android/blob/a48a9c564c3ad5e18f1076c7521379fbfe6d669d/src/Xamarin.Android.Build.Tasks/Tasks/AndroidAdb.cs) fails.  What gets reported to the end-user is:

```
MSB6006: "adb.exe" exited with code 1.
```

To your [earlier point](https://github.com/xamarin/xamarin-android-tools/issues/208#issuecomment-1595209469)

> * […`ToolTask`] already prints all output as `Normal` importance messages when tool execution does not complete successfully.

"Normal" message importance doesn't help *us* when issues are filed and the only "useful" output is the warning or error message contents.  In order to obtain "Normal" message importance we would need to request that the customer (possibly) increase build verbosity (e.g. if it's "quiet" verbosity, "Normal" won't be logged!) and then re-run their build.  This is extra complexity and customer interaction that would be nice to avoid.

**Comment by jonpryor** [comment]
Alternatively, the issue with https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1875239 is that `<Exec/>` is used and *not* `<AndroidAdb/>`.  The underlying point remains, though: `<AndroidAdb/>` doesn't capture tool output, so if (when) `adb` errors out, there is no "trivial" way to present the `adb` output to the user.  (This in turn implies that we should *replace* all `<Exec Command="…adb…"/>` usage with `<AndroidAdb/>` usage…)

**Comment by pjcollins** [comment]
Good point about Normal message priority, I overlooked the fact that Minimal verbosity is likely commonly used. I agree that there are a couple of clear areas of improvement highlighted with this latest issue. I'll try to revisit this in the near-ish future.

**Comment by pjcollins** [comment]
I think we can close this as fixed via:

https://github.com/xamarin/xamarin-android-tools/commit/1ea4e35eaf3fe09b9ca8adf0a29b4d9988146338
https://github.com/xamarin/xamarin-android/commit/771ee1dfaaa4d3fdd96e7bcca5ac0bce1c8b6d97
