### ISSUE TITLE
Logging output is too verbose

### ISSUE THREAD

**Issue by nbevans** [xamarin/xamarin-android-tools#26]
https://github.com/xamarin/xamarin-android-tools/blob/7dc8ce8336ac26ada87f4a95a410d861ba672afa/src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs

Since updating to VS 15.6.x we have noticed that the log output being emitted by this file is too verbose. It is using TraceLevel.Info for what should surely be Debug or something similar.

Alas we are seeing this noise in our build logs:

```
  Key HKCU\SOFTWARE\Xamarin\VisualStudio\15.0_f147ecf6\Android\AndroidSdkDirectory found:
    Path contains adb in \platform-tools (C:\Users\nbevans\AppData\Local\Android\android-sdk).
  Key HKCU\SOFTWARE\Xamarin\VisualStudio\15.0_f147ecf6\Android\AndroidNdkDirectory not found.
  Key HKCU\SOFTWARE\Xamarin\VisualStudio\15.0_f147ecf6\Android\JavaSdkDirectory found:
    Path contains jarsigner.exe in \bin (C:\Program Files\Java\jdk1.8.0_131).
Looking for Android NDK...
  Key HKCU\SOFTWARE\Xamarin\VisualStudio\15.0_f147ecf6\Android\AndroidNdkDirectory not found.
  Key HKLM\SOFTWARE\Xamarin\VisualStudio\15.0_f147ecf6\Android\AndroidNdkDirectory not found.
```

The build completes successfully so all these "not found" etc warnings seem superfluous.

**Comment by jonpryor** [comment]
Entirely accidentally, PR #32 fixes this by removing those messages...
